export class ConstantUI {
  static readonly PERCENT_100 = '100%';
  static readonly PERCENT_80 = '80%';
  static readonly PERCENT_75 = '75%';
  static readonly PERCENT_60 = '60%';
  static readonly PERCENT_48 = '48%';
  static readonly PERCENT_25 = '25%';
  static readonly PERCENT_20 = '20%';
  static readonly PERCENT_15 = '15%';
  static readonly PERCENT_12 = '12%';
  static readonly PERCENT_10 = '10%';
  static readonly PERCENT_8 = '8%';
  static readonly PERCENT_5 = '5%';
  static readonly PERCENT_4 = '4%';
  static readonly PERCENT_3 = '3%';
  static readonly PERCENT_2 = '2%';
  static readonly PERCENT_1 = '1%';
}